<?php

/**
 * @file
 * Contains customer.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\migrate\MigrateExecutable;
use Drupal\migrate\MigrateMessage;

/**
 * Implements hook_help().
 */
function customer_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the customer module.
    case 'help.page.customer':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Customer Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_cron().
 */
function customer_cron() {
  $migration = \Drupal::service('plugin.manager.migration')->createInstance('customer_csv_import');
  $executable = new MigrateExecutable($migration, new MigrateMessage());
  $executable->import();
}
